#http://apps.timwhitlock.info/emoji/tables/unicode

grinning = '😁'  #grinning face with smiling eyes
tears_of_joy = '😂'  #face with tears of joy
smiling = '😃'	#smiling face with open mouth
smiling2 = '😄'  #smiling face with open mouth and smiling eyes
smiling3 = '😅'  #smiling face with open mouth and cold sweat
smiling4 = '😆'  #smiling face with open mouth and tightly-closed eyes
winking = '😉'  #winking face
smiling5 = '😊'  #smiling face with smiling eyes
delicious = '😋'  #face savouring delicious food
relieved = '😌'  #relieved face
smiling_heart = '😍'  #smiling face with heart-shaped eyes
smirking = '😏'  #smirking face
unamused = '😒'  #unamused face
cold_sweat = '😓'  #face with cold sweat
pensive = '😔'  #pensive face
confounded = '😖'  #confounded face
kiss = '😘'  #face throwing a kiss
kiss2 = '😚'  #kissing face with closed eyes
tongue_out = '😜'  #face with stuck-out tongue and winking eye
tongue_out2 = '😝'  #face with stuck-out tongue and tightly-closed eyes
disappointed = '😞'  #disappointed face
angry = '😠'  #angry face
pouting = '😡'  #pouting face
crying = '😢'  #crying face
persevering = '😣'  #persevering face
triumph = '😤'  #face with look of triumph
disappointed_relieved = '😥'  #disappointed but relieved face
fearful = '😨'  #fearful face
weary = '😩'  #weary face
sleepy = '😪'  #sleepy face
tired = '😫'  #tired face
bawling = '😭'  #loudly crying face
cold_sweat = '😰'  #face with open mouth and cold sweat
screaming_fear = '😱'  #face screaming in fear
astonished = '😲'  #astonished face
flushed = '😳'  #flushed face
dizzy = '😵'  #dizzy face
medical_mask = '😷'  #face with medical mask
grinning2 = '😸'  #grinning cat face with smiling eyes
tears_of_joy2 = '😹'  #cat face with tears of joy
smiling6 = '😺'  #smiling cat face with open mouth
smiling_heart2 = '😻'  #smiling cat face with heart-shaped eyes
smiling_wry = '😼'  #cat face with wry smile
kiss3 = '😽'  #kissing cat face with closed eyes
pouting2 = '😾'  #pouting cat face
crying2 = '😿'  #crying cat face
weary2 = '🙀'  #weary cat face
no_good = '🙅'  #face with no good gesture
okay = '🙆'  #face with ok gesture
bowing = '🙇'  #person bowing deeply
see_no_evil = '🙈'  #see-no-evil monkey
hear_no_evil = '🙉'  #hear-no-evil monkey
say_no_evil = '🙊'  #speak-no-evil monkey
happy = '🙋'  #happy person raising one hand
celebration = '🙌'  #person raising both hands in celebration
frowning = '🙍'  #person frowning
pouting3 = '🙎'  #person with pouting face
praying = '🙏'  #praying hands